### ISSUE TITLE
[전체 디자인] 웹 페이지 디자인 개선

### ISSUE THREAD

**Issue by byObin** [vuln-serch-engine-project-by-KSJ13th/main#8]
## 설명
- 사용성과 가시성 개선을 위해 bootstrap을 적용해 웹 페이지 디자인을 개선합니다. 

## TODO
- [ ] 메인 화면 디자인
- [ ] 검색 화면 디자인
- [ ] 검색 결과 출력 화면 디자인
- [ ] 차트 디자인
